### PR TITLE
feat: add the project files needed for the safari browser extension

### PR DESCRIPTION
**Pull request by qqqzhch**
## Description

mask plugin ported to the safari extension, create the files needed for the xcode

It is still in the testing phase and has not yet been successfully implemented to run the mask extension in the safari browser.

- #1271 

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

**Comment by Jack-Works** [comment]
How can the XCode project refer to our extension output? Our build is at `/dist` or `/build`, can the XCode project point to the outside of the folder, or can we use a symlink to do that?

**Comment by qqqzhch** [comment]
> 
After the mv3 build is complete, copy the build folder to the XCode project.
packages/mask-safari/mask-safari Extension/Resources/build

Because the copy will also copy manifest.json to the build directory, manifest.json needs to be placed in the Resources directory.
So manifest.json needs some file path modification, I plan to modify a manifest.json by hand first, and use it for debugging and testing

**Comment by Jack-Works** [comment]
Copy... 😂 that sounds inefficient

**Comment by qqqzhch** [comment]
@Jack-Works I added some scripts  in package.json
"destroy": "rm -rf './packages/mask-safari/mask-safari Extension/Resources/build/'*",
 "copy": "cp -r build/* './packages/mask-safari/mask-safari Extension/Resources/build'"
after  npm run build:mv3
run  npm run destroy and  npm run copy
The file can then be copied to the target location
By modifying some webpack-related configuration, since the copied app files are in the build directory
manifest.json I haven't copied it yet, now I need to edit it manually or copy it over
It now loads properly in the browser and sees the error message
WX20230513-210040@2x

**Comment by qqqzhch** [comment]
> Copy... 😂 that sounds inefficient

I think it's acceptable because it's not copied during live compilation, but after the mv3 build is completed.

**Comment by qqqzhch** [comment]
A little more progress has been made and it is already possible to load all files in the Background

**Pull request closed without merging**
