### PR TITLE
fix: revert upgrade of mui

### PR DESCRIPTION
**Pull request by UncleBill**
https://mask.atlassian.net/browse/MF-2323
https://mask.atlassian.net/browse/MF-2200

### CODE REVIEW

**Comment by Jack-Works** [comment]
interesting. let me see the changelog of mui

**Comment by Jack-Works** [comment]
the only related commit is https://github.com/mui/material-ui/pull/33168/, you can merge this revert first and I will investigate this later.

**Comment by guanbinrui** [comment]
Can we merge this now?

**Comment by Jack-Works** [comment]
yes, please merge

**Review by Jack-Works — APPROVED** [review]

**Pull request merged**
