### PR TITLE
feat(network): add Fantom network on Mask 

### LINKED ISSUE #4865: [Bounty] Integrate FANTOM into Mask
## Catalogue

- Platform
  - [x] Gitcoin
  - [ ] Hackerlink
  - [ ] Mask
- Experience
  - [ ] Beginner
  - [ ] Intermediate
  - [x] Advanced
- Category
  - [ ] Mask Core Feature
  - [x] Mask Plugin
  - [ ] Security/Cryptography Feature
  - [ ] Documentation
  - [ ] Design
  - [ ] Other
    - [ ] /_List it here_/
- Time Commitment
  [x] 4 weeks

- Bounty Size
  [x] $5000

### Part 1: Problem Description

**Background** Fantom is a high-performance, scalable, and secure smart-contract platform. It is designed to overcome the limitations of previous-generation blockchain platforms. Fantom is permissionless, decentralized, and open-source.

**Solution** As the first step of our cooperation, we, Mask Network, would like to integrate Fantom as one of our default supported blockchain system in our internal Mask Wallet, so that further on-chain interactions would happen directly within Mask Network without leaving the platform. We believe this would further help us attract more users from different projects, aiming at different goals to maximize users experiences in the broad blockchain world.
If you are interested in this bounty, please make sure that you contact us first to see how our structure looks like and proceed to the development afterwards.

### Part 2: Resources

- https://fantom.foundation/
- https://github.com/DimensionDev/Maskbook/tree/master/packages/maskbook/src/plugins/Wallet

**Part 3: Contact and Support**
@yisiliu for ideas @Jack-Works for implementations Mask Network discord server: https://discord.gg/4Xccj7a75Q Fantom discord server: https://discord.com/invite/zS4Ek4WByA/

### PR DESCRIPTION
**Pull request by developerfred**
Fantom Network Integration 

closes #4865

### CODE REVIEW

**Comment by UncleBill** [comment]
@developerfred thanks for your PR. I am sorry to tell that there's already a PR submitted by me for the issue https://github.com/DimensionDev/Maskbook/pull/5036

**Comment by developerfred** [comment]
> @developerfred thanks for your PR. I am sorry to tell that there's already a PR submitted by me for the issue #5036

Awesome @UncleBill, Hadn't seen it, I'm going to close this PR and notify in the gitcoin bounty

**Comment by developerfred** [comment]
@UncleBill Are you stuck on something in your Pull Request?

**Comment by UncleBill** [comment]
> @UncleBill Are you stuck on something in your Pull Request?
> 
> 

Although it conflicts with upstream, the function is already OK. I'm waiting for merging the PR of supporting selo, then I will resolve the conflicts.

**Comment by developerfred** [comment]
> > @UncleBill Are you stuck on something in your Pull Request?
> 
> Although it conflicts with upstream, the function is already OK. I'm waiting for merging the PR of supporting selo, then I will resolve the conflicts.

@UncleBill 
Ok, good job. If you need something just drop me. I will close the pull request

**Pull request closed without merging**
