### PR TITLE
feat(plugin-infra): expose fetch{,JSON} to plugins as network API

### PR DESCRIPTION
**Pull request by UncleBill**
move them from mask package to plugin-infra package

## Description

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly in hard-to-understand areas.
- [x] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

**Comment by Jack-Works** [comment]
This change doesn't correct.

**Review by Jack-Works — CHANGES_REQUESTED** [review]
1. `fetch` and `fetchJSON` are doing network requests, thus they must be provided via Plugin initialization context.
2. If it used in content script, it must be delegated to the background page.

**Comment by UncleBill** [comment]
> 1. `fetch` and `fetchJSON` are doing network requests, thus they must be provided via Plugin initialization context.
> 2. If it used in content script, it must be delegated to the background page.

It's not used directly but via the `Worker`, the background part of this plugin. And these APIs are allowed to use in Worker of a plugin only.

**Comment by Jack-Works** [comment]
I'll draft a new PR to do it correctly tomorrow.

**Pull request closed without merging**
