### PR TITLE
chore: ito gas estimate

### PR DESCRIPTION
**Pull request by zhouhanseng**
closes #

### CODE REVIEW

**Comment by wenluomask** [comment]
After unlock the token, I cannot keep going and the button will display "enter amount" or "invalid amount".
Screen Shot 2021-12-13 at 6 08 07 PM
Screen Shot 2021-12-13 at 6 24 09 PM

**Comment by zhouhanseng** [comment]
@wenluomask because the input amount is not right

**Comment by zhouhanseng** [comment]
@wenluomask because the input amount is not right

**Comment by wenluomask** [comment]
This pr fixed the issue, which is failure of ITO submission with "Subtraction overflow" error message, after unlock token immediately.

Checked.

**Review by guanbinrui — APPROVED** [review]

**Review by yanzhihong23 — APPROVED** [review]

**Pull request merged**
