### PR TITLE
chore(just): pointless rearrangement

### PR DESCRIPTION
**Pull request by Artoria2e5**

### CODE REVIEW

**Comment by SunriseFox** [comment]
Today we made a new agreement, that only after you open an issue explaining what you want to do, and have objections settled, then shall you begin to make changes. Let us obey this rule.

**Comment by Artoria2e5** [comment]
That's some really unnecessary thing done for a chore-level task with three lines of diff.

**Comment by Jack-Works** [comment]
@sunrisefox pull request is also a kind of issue. (They share the same ID queue in the GitHub)

**Comment by SunriseFox** [comment]
@Jack-Works No, we have to discuss before actually making changes.

**Pull request merged**
