### PR TITLE
fix: add more case support

### PR DESCRIPTION
**Pull request by zhouhanseng**
Support
```jsx
const message = 'message'
const message1 = 'message1'
const message2 = 'message2'

t(message)

t(isTrue ? message1 : message2)

<UIComponent i18nKey={message}>
```

### CODE REVIEW

**Comment by zhouhanseng** [comment]
@Jack-Works https://github.com/DimensionDev/Maskbook/blob/master/src/plugins/FileService/components/Upload.tsx#L101

**Review by Jack-Works — DISMISSED** [review]

**Comment by zhouhanseng** [comment]
Resolve conflict, Please approving again.

**Review by Jack-Works — APPROVED** [review]

**Comment by Jack-Works** [comment]
hmm sorry, it seems conflict again...

**Comment by zhouhanseng** [comment]
@Jack-Works That's ok, I'd like to close this one then create a new PR. And by the way, I'm not authorized to merge PR, so plz help me to merge it, if it looks good to you, thanks!

**Pull request closed without merging**
