### PR TITLE
feat: isolate CSS per plugin, close #4847

### LINKED ISSUE #4847: [Demand] Plugin-scoped ShadowRoot isolation
We should isolate plugins into their own Shadow DOM.

### PR DESCRIPTION
**Pull request by Jack-Works**
closes #

### CODE REVIEW

**Comment by Jack-Works** [comment]
This PR changes how the plugin renders. Please check if there is any new CSS problem than the main branch. @DimensionDev/qa

**Comment by Jack-Works** [comment]
This PR changes how the plugin renders. Please check if there is any new CSS problem than the main branch. @DimensionDev/qa

**Comment by wenluomask** [comment]
Could you merge develop to this pr? And if you don't mind, I want to arrange it to 2.3.0, not 2.2.0.

**Comment by Jack-Works** [comment]
@wenluomask hi is it ok now?

**Comment by wenluomask** [comment]
1. Swap pages are missing background color of cards and buttons;
Screen Shot 2021-12-09 at 5 14 04 PM
Screen Shot 2021-12-09 at 5 15 15 PM

**Comment by wenluomask** [comment]
2. The padding and margin of transaction confirmation prompt seems are narrower than develop.
Screen Shot 2021-12-10 at 11 55 13 AM
Screen Shot 2021-12-10 at 11 56 09 AM

**Comment by Jack-Works** [comment]
@wenluomask hi plz try again. only regressions (what different than develop branch) should be counted in

**Comment by wenluomask** [comment]
#1 is fixed but #2 still existed.

3. Network Connecting page is missing the red background of Note;
Screen Shot 2022-02-14 at 4 15 40 PM

4. Token list is missing the search input box's boarder;
Screen Shot 2022-02-14 at 4 45 08 PM

5. Delete the 16px padding in Collectible plugin's make offer pages;
Screen Shot 2022-02-14 at 4 43 53 PM

6. The boarder of gas price option in Swap's gas price setting page is missing;
Screen Shot 2022-02-14 at 4 50 34 PM

7. The background of Note is missing in Confirm swap pages;
Screen Shot 2022-02-14 at 4 52 49 PM

**Comment by Jack-Works** [comment]
@wenluomask 😂 what about now?

**Comment by wenluomask** [comment]
Unable to test since it was unresponsive when I tried to enter Compose or plugins.

https://user-images.githubusercontent.com/85149605/154894849-afb986d9-abb6-49f9-9c95-7b72e2a8d976.mov

**Comment by Jack-Works** [comment]
I'm starting to rewrite this PR.

**Pull request closed without merging**
