### PR TITLE
doc: put a logo there because it's fun

### PR DESCRIPTION
**Pull request by Artoria2e5**
hope jsdelivr guys are fine with that 6kb image

### CODE REVIEW

**Comment by Jack-Works** [comment]
🤔I don't know jsdeliver can host package that not published on npm

**Comment by Artoria2e5** [comment]
🤔they have a github cdn feature but i am surprised that it works on pngs too

**Comment by neruthes** [comment]
Please make sure all usages comply with <https://maskbook.com/brand-guide/>.

**Comment by neruthes** [comment]
No code changes; skipping code review.

**Pull request merged**
