### PR TITLE
chore: reduce images w/ ImageOptim (saved 297 KB)

### PR DESCRIPTION
**Pull request by septs**
image

### CODE REVIEW

**Comment by Jack-Works** [comment]
@guanbinrui will it effect the picture based encryption?

**Comment by Tedko** [comment]
@binrui

**Comment by guanbinrui** [comment]
@Jack-Works @Tedko It's OK. Our image encoding works as long as the size of the picture does not change.

**Comment by Tedko** [comment]
👍👍

**Comment by neruthes** [comment]
Reduce bytes used! 🎉

**Pull request merged**
