### PR TITLE
feature: add a tip for prove of bio

### PR DESCRIPTION
**Pull request by Jack-Works**
image

### CODE REVIEW

**Comment by guanbinrui** [comment]
I will create a new pull request which both support this feature in twitter and facebook.

**Comment by Jack-Works** [comment]
> I will create a new pull request which support this feature both in twitter and facebook.

Maybe I should do a rebase

**Comment by guanbinrui** [comment]
> Maybe I should do a rebase

You can do a rebase in that PR which will include everything in thie PR.

**Comment by Jack-Works** [comment]
Rebased

**Pull request closed without merging**
