### PR TITLE
perf: adopt prebuilt for ios

### PR DESCRIPTION
**Pull request by Jack-Works**
please update to latest webextension-shim to test this pr

### CODE REVIEW

**Comment by Jack-Works** [comment]
does it fast?🤔 @SunriseFox

**Comment by SunriseFox** [comment]
It is fast but it doesn't work...

**Comment by Tedko** [comment]
h😂

**Comment by Jack-Works** [comment]
@SunriseFox 👀 this pr has been rebased from ios-upgrade and picked commits from #881 I think we can test the performance and functionality on iOS now...?

**Comment by Jack-Works** [comment]
redir to #885

**Pull request closed without merging**
