### PR TITLE
ITO Plugin UI

### PR DESCRIPTION
**Pull request by lelenei**

### CODE REVIEW

**Comment by Jack-Works** [comment]
@guanbinrui I found this PR has some shared changes with #2027

**Comment by guanbinrui** [comment]
> @guanbinrui I found this PR has some shared changes with #2027

Hi @lelenei, I think we should change the base to #2008.

**Comment by septs** [comment]
@lelenei plz resolve conflict, thanks.

**Comment by lelenei** [comment]
conflect fixed

**Comment by guanbinrui** [comment]
The changes have been picked https://github.com/DimensionDev/Maskbook/pull/1978/commits/c9e54097ebd768a287bcdef3a432745df0ca6c9e. Future commits push to #1978.

**Pull request closed without merging**
