### PR TITLE
feat: add hint in bio (facebook only)

### PR DESCRIPTION
**Pull request by SunriseFox**
#327, this implementation reused `resolveLastRecognizedIdentityFacebook.ts`. At least there is one...

Desktop:
image

Mobile:
image

It is not checking the bio but checking our database if it HAS been stored. This hint won't show if you just view someone's profile without any encrypted post observed.

### CODE REVIEW

**Comment by Jack-Works** [comment]
Should create a new function in the Social Network UI. Like inspectProfile()

**Comment by Tedko** [comment]
> Should create a new function in the Social Network UI. Like inspectProfile()

+1

**Comment by SunriseFox** [comment]
I'm not quite good at creating a new function...

**Comment by Tedko** [comment]
Hi Jack

**Comment by SunriseFox** [comment]
This shall be solved in #364.

**Pull request closed without merging**
