### PR TITLE
refactor: migrate ConfirmDialog

### PR DESCRIPTION
**Pull request by lelenei**
## Description

Closes mf-4347

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

**Comment by UncleBill** [comment]
But it would be not easy to create a stack of Confirm dialogs.

**Comment by guanbinrui** [comment]
> But it would be not easy to create a stack of Confirm dialogs.

It should be a modal dialog. And for a modal dialog should only create once at the same time.

**Comment by Jack-Works** [comment]
both reasonable, but I prefer the ability of multiple instance

**Comment by UncleBill** [comment]
> And for a modal dialog should only create once at the same time.

```typescript
```

**Comment by UncleBill** [comment]
> And for a modal dialog should only create once at the same time.

Here is a case.

```typescript
// Task 1
await sendingTx() // will be resolved later
await singletonConfirm.openAndWaitForClose()

// The Task 1 is still pending, and another dialog opens
await singletonConfirm.open()
```

**Comment by guanbinrui** [comment]
```typescript
// Task 1
await sendingTx() // will be resolved later
await singletonConfirm.openAndWaitForClose() // similar to window.confirm() but promise based.

// The Task 1 is still pending, and another dialog opens
await singletonConfirm.open()
```

The modal dialog has been closed after awaiting `openAndWaitForClose` to be resolved.

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
