### PR TITLE
refactor: avoid put plugin assets in public folder

### PR DESCRIPTION
**Pull request by zhouhanseng**

### CODE REVIEW

**Comment by Jack-Works** [comment]
Is that working well? If not plz call me to fix it. (The new URL and import.meta part)

**Comment by zhouhanseng** [comment]
It works well on my machine and ci build, but not works on the machine of @guanbinrui

**Comment by Jack-Works** [comment]
Plz make sure webpack-target-webextension in your node_modules is 0.4.0 not 0.3.0 (remember the npm bug) @guanbinrui

**Comment by guanbinrui** [comment]
Will be included in #2207. So close this PR.

**Pull request closed without merging**
