### PR TITLE
Fix calling writeProfileOnGun too many times

### PR DESCRIPTION
**Pull request by guanbinrui**
#562

### CODE REVIEW

**Comment by SunriseFox** [comment]
It still writes unrelated people to the indexed DB... Is this intended or a kind of bug too?

image

this relates to #541

**Comment by guanbinrui** [comment]
Hi @SunriseFox try to comment out line 122 in `src/social-network-provider/twitter.com/ui/fetch.ts`

```typescript
  // Services.Identity.updateProfileInfo(postBy, {
  //     nickname: name,
  //     avatarURL: avatar,
  // }).then()
```

Does it trigger the option menu faster?

**Comment by SunriseFox** [comment]
I just wonder why should we store irrelevant people into our database...

**Comment by guanbinrui** [comment]
Maybe prepare for some features in the future.

On the other side I think we should optimize `updateProfileInfo` make it able to skips redundant profiles (There could be many tweets in timeline from same user at the same time).

**Comment by SunriseFox** [comment]
I think it is a bit wired as when browsing twitter's news feeds or topics, lots of people are added.

**Pull request merged**
