### PR TITLE
The image payload for mobile Maskbook

### LINKED ISSUE #976: [Bug] Fix image based payload on Maskbook Mobile
# Bug Report
For now these are several problems about image based payload on Mobile

- [x] Cannot compose image based payload on Maskbook iOS/Android

- [ ] Fb only: Hard to fetch proper img for decryption on facebook mobile site.

- [x] Fix decrypt image based payload for **Twitter mobile site**

### System

- OS:
- OS Version:

### Browser

- Browser:
- Browser Version:

### Maskbook

- Maskbook Version:
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

### PR DESCRIPTION
**Pull request by guanbinrui**
+ [x] Compose image payload on mobile twitter
+ [x] Fetch & decypte image payload on mobile twitter
+ [ ] Fetch & decrypt image payload on mobile facebook
+ [ ] Compose image payload on Maskbook Android/iOS

Close #976

### CODE REVIEW

**Comment by Tedko** [comment]
Any update on this?

**Comment by Tedko** [comment]
For 
-Fetch & decrypt image payload on mobile facebook
- Compose image payload on Maskbook Android/iOS

It might be affetced by FB's new UI soon. @guanbinrui let's merge the twitter part first?

**Comment by Tedko** [comment]
@septs can you help on this pr. Need to merge the twitter part 1st

**Comment by Tedko** [comment]
> @septs can you help on this pr. Need to merge the twitter part 1st

cc @jk234ert

**Comment by Tedko** [comment]
@guanbinrui lets merge the twitter part 1st

**Comment by septs** [comment]
@Tedko this pr, over 6 months no any update. should be closed and delete branch.

**Comment by Tedko** [comment]
@guanbinrui @jk234ert may need work this out together.

see https://twitter.com/yuan_brad/status/1312550251480317952

1. Compose image payload on mobile twitter (not sure if this is fixed already on Android? seems not)
2. Fetch & decrypt image payload on mobile twitter  (this is published in store ver of Android already and should got iOS ver soon? )- seems this is fixed already?

**Pull request closed without merging**
