### PR TITLE
chore: add fields for gecko in the manifest

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Review by septs — APPROVED** [review]

**Review by Tedko — CHANGES_REQUESTED** [review]
Change the description to "Maskbook is a portal to the new, open internet. With Maskbook, you can send encrypted posts to your friends, participate in cryptocurrency lucky-draws, and share encrypted files on the platforms you are already using."

**Comment by Tedko** [comment]
@guanbinrui @Jack-Works release a hotfix after changing the descriptions-

**Comment by Jack-Works** [comment]
@Tedko "String is longer than the maximum length of 132."

**Comment by Tedko** [comment]
ok.. will open a specific issue later

**Pull request merged**
