### PR TITLE
feature: add author id in payload

### LINKED ISSUE #1258: [Demand] Remove username consistency requirement for users
## Metadata

Field | Value
--- | ---
Previous Stage | ...
Figma Link | Figma_Link_Here____
Expected UX prototype due | 2020-W??-5
Actual UX prototype release | -
Expected engineering due | 2020-W??-5
Corresponding Pull Request | -
Completion Version | -

## Introduction

It is previously implemented that the current username of the publisher is involved in determining the PostKey during decryption. This would require users that they must never change their username, or their previous posts will be doomed.

We will need to change this behavior.

## Source Verification Notice

When composing a Post, the username of the currently using Profile shall be added to the Post.

When viewing a Post, the username should match the indicated username. If not matching, Maskbook adds a small line of notice below the content of the decrypted post, which is similar to how Twitter shows the original uploader of videos when videos are being tweeted by a different account.

## Notes

- None.

### PR DESCRIPTION
**Pull request by Jack-Works**
close #1258

### CODE REVIEW

**Comment by Jack-Works** [comment]
need a reviewer (not only code) cc @neruthes

**Review by neruthes — APPROVED** [review]
LGTM (i18n). Other parts are left for others to review.

**Review by Tedko — APPROVED** [review]

**Comment by Tedko** [comment]
lgtm

**Review by septs — DISMISSED** [review]

**Comment by Jack-Works** [comment]
Please don't merge now. @neruthes may want to say something

**Review by Tedko — DISMISSED** [review]
The Japanese i18n LGTM @Jack-Works

**Comment by septs** [comment]
plz fix type checking error.

**Comment by Jack-Works** [comment]
wait, i thought @neruthes says that we don't do this in this year?

**Comment by Tedko** [comment]
> wait, i thought @neruthes says that we don't do this in this year?

ok then ignore this for now

**Comment by Tedko** [comment]
hey let's keep doing this - this is needed to solve the red packet / name change dilemma 
@Jack-Works this LGTM; any review @septs ?

**Comment by septs** [comment]
plz fix build failed.

**Pull request merged**
