### PR TITLE
refactor: remove unused code from trader plugin

### PR DESCRIPTION
**Pull request by guanbinrui**
## Description

Remove a bunch of code that is not used in the Trader plugin.

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [x] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

### CODE REVIEW

**Comment by nuanyang233** [comment]
Plz remove the unused locale key.

**Comment by UncleBill** [comment]
@septs Could you help to update the gulp task `locale-kit`, make it fail at CI if there are unused locale keys.

**Comment by UncleBill** [comment]
> @septs Could you help to update the gulp task `locale-kit`, make it fail at CI if there are unused locale keys.

It would be perfect if there is a bot can provide suggestion patch in the PR.

**Comment by guanbinrui** [comment]
> Plz remove the unused locale key.

Removed.

**Pull request merged**
