### PR TITLE
Prevent from creating persona if name or password absent

### LINKED ISSUE #961: [Bug] Empty name and empty password are not prohibited for Persona creation
# Bug Report

### Maskbook

- Maskbook Version: *
- Installation: CI Artifact
- Build Commit: a921183eb9988850fd90a62f548f94b75094845f

### Expected Behavior

Should show a tooltip-like alert at the input element which tells the user that:

Language | String
--- | ---
en | Name cannot be empty
zh | 名稱不能為空

### Actual Behavior

image

### How To Reproduce

Create a Persona with empty name.

### PR DESCRIPTION
**Pull request by guanbinrui**
close #961

Screen Shot 2020-04-10 at 2 31 50 PM
Screen Shot 2020-04-10 at 2 32 38 PM

### CODE REVIEW

**Comment by SunriseFox** [comment]
maybe we can directly commit them to the new dashboard... things may have changed a lot.

**Comment by Tedko** [comment]
> maybe we can directly commit them to the new dashboard... things may have changed a lot.

@guanbinrui

**Comment by neruthes** [comment]
Looks good but is it possible to prompt the error alert around the input itself like changing the state of the input?

**Comment by Jack-Works** [comment]
Wait this UI is wired. I agree with @neruthes

> Looks good but is it possible to prompt the error alert around the input itself like changing the state of the input?

image

Please check out https://material.io/components/text-fields/ @guanbinrui

**Comment by guanbinrui** [comment]
> Wait this UI is wired. I agree with @neruthes
> 
> > Looks good but is it possible to prompt the error alert around the input itself like changing the state of the input?
> 
> image
> 
> Please check out https://material.io/components/text-fields/ @guanbinrui

That makes sense!

**Pull request merged**
