### PR TITLE
fix: match DHedge pools from main and staging URLs

### PR DESCRIPTION
**Pull request by iRhonin**
This PR has these changes:
  - Show DHedge Pools independent of chain (https://app.dhedge.org and https://dh-pre-prod.web.app)
  - Passing Pool URL from top component to the children
  - Fixed a bug related to balance formating in the share message

https://github.com/dhedge/dhedge-docs/issues/3

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

**Comment by guanbinrui** [comment]
@AinuX Would you please test this build?

**Review by Jack-Works — APPROVED** [review]

**Comment by AinuX** [comment]
> @AinuX Would you please test this build?

Checked

**Comment by guanbinrui** [comment]
@iRhonin Would you please resolve those conflicts?

**Comment by iRhonin** [comment]
> @iRhonin Would you please resolve those conflicts? TY.

@guanbinrui Done.

**Comment by wenluomask** [comment]
For the part show DHedge Pools independent of chain, it is inconsistent with other plugins.
Here is what should be happened:

1. If no wallet connected, show the plugin card normally, but show "connect a wallet" button once you open the invest pop up;
Screen Shot 2021-08-03 at 3 45 19 PM
Screen Shot 2021-08-03 at 3 46 40 PM

2. If wallet is connected and the pool is supported in current chain, show pool normally;

3.  If wallet is connected but the pool is not supported in current chain, the whole plugin card only show "Not available on xxx Network" and "Switch to xxx Network" button;
Screen Shot 2021-08-03 at 3 53 32 PM

**Comment by wenluomask** [comment]
For a pool that holds more than 50% of the pool, it is showing holding 100% in plugin. You can check my tweet: https://twitter.com/WEN6666661/status/1422460169494032388

Screen Shot 2021-08-03 at 3 58 07 PM
Screen Shot 2021-08-03 at 3 58 16 PM

**Review by Jack-Works — DISMISSED** [review]

**Comment by guanbinrui** [comment]
@iRhonin, Would you please check those issues reported by @wenluomask? Thanks!

**Comment by iRhonin** [comment]
Good catches @wenluomask! Fixed all.

P.S: Added a row to `messages` for more than 50%: `plugin_dhedge_manager_share_more_than_50`

**Comment by wenluomask** [comment]
Checked.

Thanks for the quick fix!

**Comment by guanbinrui** [comment]
@iRhonin Run `npx gulp locale-kit --sync-keys` to sync locale keys.

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
