### PR TITLE
chore: change domain to gun.maskbook.io related [#176]

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by Jack-Works** [comment]
> What about getting a SSL cert and switch to HTTPS...?

@neruthes @Tedko Should we?

cc @asonmine @yisiliu

**Comment by neruthes** [comment]
Just wondering why `.io` instead of `.com` 🤔

**Comment by neruthes** [comment]
I think CloudFlare can be enough in most cases.

**Comment by SunriseFox** [comment]
But Cloudflare won't proxy any ports other than 80/443... If we use it, we need to switch to 443 port (recommended).

**Comment by Jack-Works** [comment]
> Just wondering why `.io` instead of `.com` 🤔

Don't you think `.io` is cooler? 🤔

> But Cloudflare won't proxy any ports other than 80/443... If we use it, we need to switch to 443 port (recommended).

It's okay to use any port for gun

**Comment by neruthes** [comment]
If GUN has an HTTPS interface, I suppose that CloudFlare is the most desirable option for now.

As for domain name, I do not find using `.io` necessary or fancy in this particular usage. Maybe I will find it cool in some other usage.

**Comment by SunriseFox** [comment]
- [x] move maskbook.io / maskbook.com's NS to Cloudflare
- [ ] configure nginx with Cloudflare's origin ssl cert on GUN's server, proxy pass to localhost:8765
- [ ] configure Cloudflare to use Cloudflare DNS for `gun.maskbook.io/.com`
- [ ] merge this

**Comment by SunriseFox** [comment]
if @yisiliu approved this idea, I should be able to deal with the server-side chores. Maybe [https://github.com/Dletta/visualGraph](https://github.com/Dletta/visualGraph) could be deployed too.

**Comment by yisiliu** [comment]
Let's do this.

**Pull request merged**
