### PR TITLE
fix: mf-2787 feed card background color

### PR DESCRIPTION
**Pull request by UncleBill**
https://mask.atlassian.net/browse/MF-2787

### CODE REVIEW

**Comment by UncleBill** [comment]
@robobun

```ts
console.log("Hello Maskbook!")
```

**Comment by robobun** [comment]
@UncleBill here you go!
```tsx
Hello Maskbook!
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("Hello Maskbook!")
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Review by Jack-Works — APPROVED** [review]

**Comment by Jack-Works** [comment]
> @robobun
> 
> ```ts
> console.log("Hello Maskbook!")
> ```

what is this 🤔🤔🤔🤔🤔🤔

**Comment by robobun** [comment]
@Jack-Works here you go!
```tsx
Hello Maskbook!
```
<details>
  <summary>Code</summary>
  
```tsx
console.log("Hello Maskbook!")
```
</details>

_Ran using the latest build of Bun, an all-in-one JavaScript runtime._

**Comment by UncleBill** [comment]
> what is this 🤔🤔🤔🤔🤔🤔

A code runner, you can checkout its profile. And more at https://twitter.com/jarredsumner/status/1593042734696497153?s=20&t=XKhq1En5ZZr2VL4_QGJz4w

**Comment by guanbinrui** [comment]
> > what is this 🤔🤔🤔🤔🤔🤔
> 
> A code runner, you can checkout its profile. And more at https://twitter.com/jarredsumner/status/1593042734696497153?s=20&t=XKhq1En5ZZr2VL4_QGJz4w

Interesting. ☕️

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
