### PR TITLE
perf: let gun1 share instance with gun2

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by Jack-Works** [comment]
@SunriseFox any progress on this?

**Comment by Jack-Works** [comment]
@sunrisefox hmm did you add the new gun server?

**Comment by SunriseFox** [comment]
I don't know if I should... No more directions since deployment.

**Comment by Tedko** [comment]
Better add this new gun instance — Did you test it?

**Comment by Jack-Works** [comment]
> Better add this new gun instance — Did you test it?

We should consider add it in another pr with more discuss

**Pull request merged**
