### PR TITLE
Disable auto share when importing backup

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by neruthes** [comment]
Can someone offer some background on this decision?

**Comment by Jack-Works** [comment]
> Can someone offer some background on this decision?

@Tedko reports when he is setting up a new Maskbook with his backup file, the Maskbook behaves very slow cause it is doing the heavy crypto calculation. I think auto-share during restoring the database is unwanted behavior.

**Comment by neruthes** [comment]
The real solution should be a better scheduling mechanism to soften the calculation burden.

At this moment I will not block this PR. We shall design the automatic sharing mechanism ASAP.

**Comment by Jack-Works** [comment]
When importing a new database, the data in the database is already shared to it's targets so it's no need to autoshare it again. @neruthes

**Comment by Tedko** [comment]
LGTM.

**Pull request merged**
