### PR TITLE
fix: polyfill not injecting css

### PR DESCRIPTION
**Pull request by SunriseFox**
previous commit does cause troubles.

### CODE REVIEW

**Comment by Jack-Works** [comment]
This can be fixed by adding a try-catch on `shadow.adoptedStylesheets = [...]`

Without this fix, it doesn't works well on Firefox

**Comment by SunriseFox** [comment]
...But how to catch it?

**Comment by Jack-Works** [comment]
See https://github.com/DimensionDev/Maskbook/commit/adb2db4501b4b4408401a593768768272dd70ef7

Feel free to cherrypick it

**Comment by SunriseFox** [comment]
observed a new warning `Warning: unmountComponentAtNode(): The node you're attempting to unmount was rendered by another copy of React.` at `renderInShadowRoot.tsx:20`

**Pull request merged**
