### PR TITLE
feat: add verification bio on create or restore

### PR DESCRIPTION
**Pull request by SunriseFox**
Something here...
image

And here:
image

### CODE REVIEW

**Comment by Jack-Works** [comment]
lgtm but what about @neruthes ?

**Comment by neruthes** [comment]
Seems that these will be removed when #369 and #407 delivered? I would refrain from encouraging it unless there is a good chance that these will remain useful after #369 and #407. 

Specifically, one more step of verification in the procedure of connecting profile can be ok, while the verification upon database restoration looks confusing to me. The user should have a chance to update profile bio after successful restoration, instead of being rejected when trying to restore.

**Comment by Jack-Works** [comment]
> Seems that these will be removed when #369 and #407 delivered? I would refrain from encouraging it unless there is a good chance that these will remain useful after #369 and #407.

we still need a bio prove after all

**Comment by neruthes** [comment]
> > Seems that these will be removed when #369 and #407 delivered? I would refrain from encouraging it unless there is a good chance that these will remain useful after #369 and #407.
> 
> we still need a bio prove after all

I believe that the test-and-verify is well included in #369 and a more intuitive profile connecting guides wizard is well documented in #409. Let me know if there is any opinion regarding the coverage of #369 and #409.

**Comment by neruthes** [comment]
## Request for changes

### State 1 (Base)

image

Looks good. No changes needed.

### State 2 (Ready)

Screen Shot 2019-12-04 at 08 55 27

2 buttons:

Position | Color | Text
Left | White | Retry
Right | Blue | Next

### State 3 (Verifying)

Screen Shot 2019-12-04 at 08 55 23

2 buttons:

Position | Color | Text
Left | White | Retry
Right | Blue (Disabled) | Verifying...

**Comment by SunriseFox** [comment]
Should have done with these changes. You may try again.

**Comment by Jack-Works** [comment]
how does the ui works on the mobile? it might be not so easy to switch between tabs

**Comment by Jack-Works** [comment]
I'm wondering if we can replace the technical word "verify" with "Check if I have set Maskbook up yet", that may reduce the confusion to users

**Comment by neruthes** [comment]
> I'm wondering if we can replace the technical word "verify" with "Check if I have set Maskbook up yet", that may reduce the confusion to users

Too long to put into a button. 🤔

**Comment by Jack-Works** [comment]
We have a new kind of verification on the bio page, does that enough? (Maybe not, not every one will check their profile page frequently)

**Comment by neruthes** [comment]
After #369 is delivered, the profile connecting procedure requires successful setup in the profile bio. #409 will further strengthen this.

**Pull request closed without merging**
