### PR TITLE
Lottery Plugin

### PR DESCRIPTION
**Pull request by RetricSu**
- feature
    - send, participate, draw, refund Lottery on chain
    - two draw mode:
        - draw when certain time is reached.
        - draw when certain amount of people participated.

- todo
    - store lottery info on local indexDB, reduce onchain request
    - suport list of lottery history
    - support mutiple-type token as prize option/add activate lottery function
    - support more draw-mode, eg: instantly draw

### CODE REVIEW

**Comment by Jack-Works** [comment]
hi! @RetricSu, we have made a big change to the repo just now. I don't have write access to your fork repo but I can tell you how to resolve the commit.

First, rebase or merge to 46af401 (the last commit before the big change), then rebase or merge to `master` branch. Thanks!

**Comment by RetricSu** [comment]
is it good now? @Jack-Works

**Comment by Jack-Works** [comment]
Cool thanks!

**Comment by septs** [comment]
@RetricSu any update?

**Comment by RetricSu** [comment]
@septs actually I have written a new contract to reduce gas cost long ago but haven't deploy yet. will try to upgrade the plugin code as well next week. sorry for the late response.

**Comment by Tedko** [comment]
> @septs actually I have written a new contract to reduce gas cost long ago but haven't deploy yet. will try to upgrade the plugin code as well next week. sorry for the late response.

cool!

**Comment by Tedko** [comment]
@RetricSu 😉

**Comment by Jack-Works** [comment]
it seems like this PR needs a great effort to rebase to the mainstream. call me if you need help! @RetricSu

**Comment by RetricSu** [comment]
> it seems like this PR needs a great effort to rebase to the mainstream. call me if you need help! @RetricSu

yea thx man. I will try to find more time to finished this PR and submit updates as soon as possible. recently kind of busy with my day job. sorry again for being late.

**Comment by yisiliu** [comment]
Closed. Anyone can re-open this pr if you would like to continue working on this.

**Pull request closed without merging**
