### PR TITLE
chore: improve special contacts list

### PR DESCRIPTION
**Pull request by zhouhanseng**
Make the height of List fixed as its initialization, won't change when searching.

image

image

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]

**Comment by septs** [comment]
@zhouhanseng i think, integrated https://github.com/bvaughn/react-highlight-words get a better UX
CC @Jack-Works

**Comment by Jack-Works** [comment]
In search? @septs 

Does it useful? 👀

**Comment by septs** [comment]
bold keyword area.

**Comment by septs** [comment]
e.q:

search: `suji`
result:
```
<b>suji</b> yan
```

**Pull request merged**
