### PR TITLE
refactor: composition dialog

### PR DESCRIPTION
**Pull request by Jack-Works**
Rewrite `PostDialog` into `CompositionDialog`.

Visible changes:

image

### CODE REVIEW

**Comment by wenluomask** [comment]
It failed to encrypt context that just for myself.
Screen Shot 2021-08-13 at 2 15 30 PM

**Comment by Jack-Works** [comment]
@wenluomask thanks, fixed

**Comment by Jack-Works** [comment]
@guanbinrui @septs plz review this

**Comment by wenluomask** [comment]
1. “Only myself and...” should be displayed fully.  
Screen Shot 2021-08-17 at 3 57 45 PM

2. Once you choose everyone option, "+mask network users" shouldn't be able to select. Only can be selected if you choose "only myself and ...";

3. Sometimes payload didn't paste automatically in encrypted post box, but paste in twitter's input box.

https://user-images.githubusercontent.com/85149605/129693098-895f04f7-c1e7-4dc6-a3bd-d943ef97f27b.mov

**Comment by Jack-Works** [comment]
> 1. “Only myself and...” should be displayed fully.

Fixed: Changed to `End to end` (encryption)

> 2. Once you choose everyone option, "+mask network users" shouldn't be able to select. Only can be selected if you choose "only myself and ...";

Fixed: When selecting `Everyone`, `+Mask Network users` won't be displayed.

> 3. Sometimes payload didn't paste automatically in encrypted post box, but paste in twitter's input box.

Cannot reproduce. I may try to review the code by myself.

**Comment by Jack-Works** [comment]
> 3. Sometimes payload didn't paste automatically in encrypted post box, but paste in twitter's input box.

Old order: Auto paste test => Encode image (time-costing) => Auto paste image

New order: Encode image (time-costing) => Auto paste image => Auto paste test

I tried to roll back to the old operation order. Does that fix the problem? @wenluomask

**Comment by wenluomask** [comment]
I think change back to Myself will be better. Payload still didn't work for the latest version.

**Comment by Jack-Works** [comment]
> I think change back to Myself will be better.

Done.

> Payload still didn't work for the latest version.

Do you mean `Sometimes payload didn't paste automatically in encrypted post box, but paste in twitter's input box.` still exists? Does it appear in the mainstream?

**Comment by wenluomask** [comment]
It doesn't appear in the mainstream.

**Comment by wenluomask** [comment]
Checked.

**Pull request merged**
