### PR TITLE
Fix can not decrypt comments

### LINKED ISSUE #863: [Bug] Cannot decrypt comments
# Bug Report

### System

- OS: MacOS Mojave
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: Version 79.0.3945.130 (Official Build) (64-bit)

### Maskbook

- Maskbook Version: 1.10.9
- Installation: Self-Complied
- Build Commit: ce02294509cbbe24220a49b9963238746af55e1e

## Bug Info

Cannot decrypt comments.

### PR DESCRIPTION
**Pull request by guanbinrui**
close #863

### CODE REVIEW

**Comment by Jack-Works** [comment]
Does it also close #811?

**Comment by guanbinrui** [comment]
> Does it also close #811?

Can not reproduce double comment boxes and comment forms.

**Comment by Tedko** [comment]
> > Does it also close #811?
> 
> Can not reproduce double comment boxes and comment forms.

You need nested encrypted comment from diff account to reproduce

**Comment by guanbinrui** [comment]
> > > Does it also close #811?
> > 
> > 
> > Can not reproduce double comment boxes and comment forms.
> 
> You need nested encrypted comment from diff account to reproduce

Screen Shot 2020-03-07 at 2 15 59 PM

It's fixed?

**Comment by Tedko** [comment]
Seems yes.

**Comment by Tedko** [comment]
@Jack-Works  double check it?

**Comment by Jack-Works** [comment]
> @Jack-Works double check it?

I'm not sure if it gets fixed

**Pull request merged**
