### PR TITLE
fix: move snackbar to top right close gh-2015

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Review by septs — COMMENTED** [review]
Mobile only? need test?

**Comment by jk234ert** [comment]
This fix should be desktop only

**Comment by jk234ert** [comment]
Tested on Chrome & Firefox
Snackbar displays at the left bottom corner, is this by design? @Jack-Works 

Snipaste_2020-12-10_16-31-54

**Comment by Tedko** [comment]
> Tested on Chrome & Firefox
> Snackbar displays at the left bottom corner, is this by design? @Jack-Works
> 
> Snipaste_2020-12-10_16-31-54

this part is ok

**Comment by Tedko** [comment]
@jk234ert  this is for https://github.com/DimensionDev/Maskbook/issues/2015

should be only related w/ desktop

**Comment by Tedko** [comment]
btw. should we add this for mobile as well? For mobile #2015 's copy button will not have any notif:
IMG_8865



We need sth like this:

IMG_8866

**Review by Tedko — APPROVED** [review]

**Pull request merged**
