### PR TITLE
toolchain for android/firefox

### PR DESCRIPTION
**Pull request by Misaka-0x447f**

### CODE REVIEW

**Comment by Jack-Works** [comment]
Why this pr has so many commits from release/1.6.0?

**Comment by Misaka-0x447f** [comment]
> 
> 
> Why this pr has so many commits from release/1.6.0?

No idea, someone rebased this. Maybe @SunriseFox did with his command line.
image

**Comment by SunriseFox** [comment]
It is quite obvious that these changes are based on release/1.6.0 branch. You are merging it to wrong branch. Don't blame me.

**Comment by Misaka-0x447f** [comment]
ok so, what to do now @SunriseFox

**Comment by Artoria2e5** [comment]
close it and make a new one with the base set to `re;ease/1.6.0` goddamnit

**Comment by Tedko** [comment]
Want to remind folks watch languages in repo and commit. We’re not Linus.

**Comment by Misaka-0x447f** [comment]
ok, wait until release 1.6 ready then cherry-pick.

**Pull request closed without merging**
