### PR TITLE
chore: hide unused entry

### LINKED ISSUE #4733: [Crash] TypeError: Cannot read properties of undefined (reading 'filter')
I was claiming token in BSC, then change to Polygon tab, then Mask reports an error.
It occured in branchj hancheng/hide-unused-entry

Screen Shot 2021-11-01 at 4 48 20 PM

> Cannot read properties of undefined (reading 'filter')

Error stack:

<pre>TypeError: Cannot read properties of undefined (reading 'filter')
    at chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/chunk.1790.js:1831:47
    at pj (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:248:366)
    at dk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:295:100)
    at ak (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:281:185)
    at fg (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:134:105)
    at tk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:292:345)
    at lk (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:290:64)
    at ck (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/npm.react-dom.js:279:210)
    at J (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/2957.js:16900:203)
    at MessagePort.R (chrome-extension://bnnkdbjkebeodldlpnjfjcicdcinkoke/js/2957.js:16901:128)</pre>

## Build info
- Version: 2.0.0
- NODE_ENV: production
- target: chromium
- build: beta
- architecture: web
- BUILD_DATE: 2021-11-01T04:30:46.831Z
- VERSION: v1.29.12-1249-g34e10f098

## Git (*):

34e10f098 (hancheng/hide-unused-entry) on tag "v2.0.0-beta"
git@github.com:DimensionDev/Maskbook.git

### PR DESCRIPTION
**Pull request by zhouhanseng**
closes #4733.

### CODE REVIEW

**Review by guanbinrui — APPROVED** [review]

**Comment by wenluomask** [comment]
Change ClaimAll/Switch xx Network button to new color: black in light mode and white in dark mode.

**Comment by wenluomask** [comment]
Polygon network is invalid in this branch.
https://github.com/DimensionDev/Maskbook/issues/4733

**Comment by zhouhanseng** [comment]
@wenluomask Fixed

**Comment by guanbinrui** [comment]
I just labeled this PR to close #4733.

**Comment by wenluomask** [comment]
1. When no wallet is connected, the UI is different from Figma. If user didn't connect any wallte yet, it will show the old connecr wallet pages. If user connected with wallet before, and then delete the wallet, it will show up like the pic below. Be careful that some spplications should be disable to enter.
Screen Shot 2021-11-03 at 11 17 59 AM
Screen Shot 2021-11-03 at 11 19 48 AM

2. Once we connect wallet by WalletConnect, there will be a disconnect button. Since I clicked the disconnect button, the QR code will flash pass but nothing happened.
Screen Shot 2021-11-03 at 11 19 48 AM

**Comment by wenluomask** [comment]
Checked except for problems about WalletConnect.

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
