### PR TITLE
chore: several fix for ito and lucky drop

### LINKED ISSUE #4967: [Bug] Should adjust the display priority of thegraph and onchain data in ITO history
### How to reproduce?
1. Create ITO
2. Check the ITO past history
3. Block thegraph api request 
4. Check the ITO past history

https://user-images.githubusercontent.com/2582974/143733985-f0da74a1-730f-496a-b7c2-d7922658bfbc.mp4

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [x] Build of version/commit hash: /dev

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by hanszhoou**
## Description

Closes #4967
https://mask.atlassian.net/browse/MASK-419
https://mask.atlassian.net/browse/MASK-581
https://mask.atlassian.net/browse/MASK-584
https://mask.atlassian.net/browse/MASK-562
## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
  - [x] I have removed all in development `console.log`s
  - [x] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

**Comment by wenluomask** [comment]
1. You should stop fetching data from the graph since the graph is useless if onchain doesn't work;
Screen Shot 2022-01-13 at 11 56 16 AM

2. Since I blocked the thegraph, it failed to fetch NFT's lucky drop history;
Screen Shot 2022-01-13 at 12 06 28 PM

3. MASK-584 didn't fix yet.

**Comment by hanszhoou** [comment]
@wenluomask NFT red packet still only rely on subgraph.

**Comment by hanszhoou** [comment]
@wenluomask fixed

**Comment by wenluomask** [comment]
Crash occurred. You can check in here: https://github.com/DimensionDev/Maskbook/issues/5447

And the max fee seems is too low for transaction. 
Screen Shot 2022-01-14 at 1 39 48 PM

**Comment by wenluomask** [comment]
Crash still exists.

**Comment by wenluomask** [comment]
Checked.

**Review by UncleBill — DISMISSED** [review]

**Review by Jack-Works — DISMISSED** [review]

**Review by Jack-Works — APPROVED** [review]

**Review by UncleBill — APPROVED** [review]

**Pull request merged**
