### PR TITLE
chore(lint): use husky to lint code and commit message

### PR DESCRIPTION
**Pull request by SunriseFox**

### CODE REVIEW

**Comment by Jack-Works** [comment]
approved

Do you mind to add check to ci file?

What about add and enforce tslint/eslint?

**Comment by SunriseFox** [comment]
> approved
> 
> Do you mind to add check to ci file?
> 
> What about add and enforce tslint/eslint?

Maybe we need to bring eslint-loader back. This shall be done at this weekend, together with other chores with respect to the toolchains.

**Comment by Jack-Works** [comment]
uhh, do we really need a git hook? Since all the codes must be merged by pull request, we can just reject the bad code in CI

What do you think?

**Comment by SunriseFox** [comment]
that seems ok.

**Comment by Jack-Works** [comment]
We will do that in #126

**Pull request closed without merging**
