### PR TITLE
upgrade: upgrade typescript to 4.2.2

### PR DESCRIPTION
**Pull request by nuanyang233**

### CODE REVIEW

**Comment by nuanyang233** [comment]
Compile after upgrading and get an  error:

```
Error: Debug Failure.
    at Object.getModuleSpecifiers (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:91587:30)
    at getSpecifierForModuleSymbol (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:39998:62)
    at createExpressionFromSymbolChain (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:40172:63)
    at symbolToExpression (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:40159:24)
    at /Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38966:106
    at withContext (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:39005:37)
    at symbolToExpression (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38966:28)
    at symbolToStringWorker (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38886:30)
    at Object.usingSingleLineStringWriter (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:10151:13)
    at symbolToString (/Maskbook/node_modules/.pnpm/typescript@4.2.2/node_modules/typescript/lib/tsc.js:38884:73)


```

**Comment by nuanyang233** [comment]
[#43011](https://github.com/microsoft/TypeScript/issues/43011)

**Comment by Jack-Works** [comment]
let's wait for 4.2.3 release

**Comment by Jack-Works** [comment]
cannot upgrade to 4.2.3 cause https://github.com/microsoft/TypeScript/issues/43098

let's wait for 4.2.4 or ts-results fix

**Comment by Jack-Works** [comment]
now blocked by https://github.com/vultix/ts-results/issues/20

**Pull request closed without merging**
