### PR TITLE
toolchain fixes

### PR DESCRIPTION
**Pull request by Misaka-0x447f**

### CODE REVIEW

**Comment by Misaka-0x447f** [comment]
By tests, npm script manager actually has ability to kill
all process spawned by node even detached.
We recommended that do not running just tasks directly,
instead, use npm scripts.

**Comment by Misaka-0x447f** [comment]
> 
> 
> I think, are we going in the wrong direction? Why should we care about how to kill a process group on *nix and Windows?

If not and not running scripts with npm script, a react-webpack dev server will remains in memory and hold the 3000 port until killed, this is a kind of memory leak.

**Comment by SunriseFox** [comment]
Well... it becomes more and more complicated (and dangerous)... which should not have to be like this. Can we just remove `just` and get webpack to do these things? Something like `config-overrides-with-linter.js` or `config-overrides-with-firefox-(android).js`...

**Comment by Misaka-0x447f** [comment]
This PR will not include chromium support because of upstream broken and not published release include this feature.

**Comment by Misaka-0x447f** [comment]
@Artoria2e5 Why should we not break down big files to smaller parts by files and folders, but comment splitter? This could be hard to indexing. Anyway, you can keep your mind, I'm not strongly recommend to break it down since it exceeds 70 lines but not 1k lines.

**Comment by Misaka-0x447f** [comment]
@Jack-Works You need to decide break down the config file or not.

**Comment by SunriseFox** [comment]
have a look at #157

**Pull request closed without merging**
