### PR TITLE
Better user experence in mobile version Twitter

### LINKED ISSUE #539: [Bug] Can not invoke compose box in mobile version twitter
# Bug Report

### System

- OS: macos mojave 
- OS Version: 10.14.6

### Browser

- Browser: Chrome
- Browser Version: 78.0.3904.108 (Official Build) (64-bit)

### Maskbook

- Maskbook Version:
- Installation: Self-Complied
- Build Commit: 142a54d10f906c2dc8f1710d6785b77dc121af7a

### Actual Behavior

Can not invoke compose box in mobile version twitter.

image

### PR DESCRIPTION
**Pull request by guanbinrui**
This PR includes:

+ Optimize dialog components  for mobile version twitter
+ Fix #539

image

### CODE REVIEW

**Comment by Jack-Works** [comment]
@guanbinrui here is a conflict now

**Comment by guanbinrui** [comment]
> @guanbinrui here is a conflict now

Resolved.

**Comment by Jack-Works** [comment]
@guanbinrui there is another conflict 🤣🤣🤣

**Comment by guanbinrui** [comment]
> @guanbinrui there is another conflict 🤣🤣🤣

I should not change same file across multiple pull requests. 😅

**Pull request merged**
