### PR TITLE
refactor: slim maskbook for firefly

### PR DESCRIPTION
**Pull request by swkatmask**

### CODE REVIEW

**Comment by Jack-Works** [comment]
looks like you removed almost everything. looks like not a correct PR. close for now

**Comment by swkatmask** [comment]
> looks like you removed almost everything. looks like not a correct PR. close for now

You don't even ask me.

This is done on purpose. We would like to fork and maintain a slim version of Maskbook with critical code only, and this fork would never be merged into Maskbook main branch.

**Comment by swkatmask** [comment]
This is done on purpose.

**Comment by Jack-Works** [comment]
> > looks like you removed almost everything. looks like not a correct PR. close for now
> 
> You don't even ask me.
> 
> This is done on purpose. We would like to fork and maintain a slim version of Maskbook with critical code only, and this fork would never be merged into Maskbook main branch.

sorry, this PR looks like a mistake so I closed it. What if the main branch made some changes, is there any plan to follow the upstream, or it will keep forked forever? If it's the latter case, I'd suggest just copy code to ff

**Comment by swkatmask** [comment]
It's OK.

> or it will keep forked forever?

Yes, it will.

> If it's the latter case, I'd suggest just copy code to ff

We might do it in the future, then Firefly can get rid of Maskbook in that day.

/cc @guanbinrui

**Pull request closed without merging**
