### PR TITLE
refactor: token list

### PR DESCRIPTION
**Pull request by guanbinrui**
closes #

### CODE REVIEW

**Review by Jack-Works — APPROVED** [review]

**Review by NikoManiac — APPROVED** [review]

**Comment by EFudd21** [comment]
> closes #
//:jp

**Comment by EFudd21** [comment]
//:jp

**Comment by EFudd21** [comment]
//:jp

**Comment by EFudd21** [comment]
//:jp

**Comment by EFudd21** [comment]
//:jp

**Comment by EFudd21** [comment]
//:jp

**Pull request merged**
