### PR TITLE
feat: search token input UI

### LINKED ISSUE #3986: [Demand] search token input UI
## Catalogue

- [x] UI/UX
- [ ] Mask Core Feature
- [ ] Mask Plugin Feature
- [ ] Security/Cryptography Feature
- [ ] Other
  - /_List it here_/

## Part 1: Introduction and Background
image

to

image

https://www.figma.com/file/gVkQ67y285b4FXVV1KPThN/Twitter?node-id=4393%3A212674

### PR DESCRIPTION
**Pull request by lelenei**
closes #3986

### CODE REVIEW

**Comment by lelenei** [comment]
image
image

**Comment by zhouhanseng** [comment]
@DimensionDev/qa

**Comment by wenluomask** [comment]
Please change to "Search Token Name or Contract Address" in input box. In addition, check the token list from dashboard's add token to make sure text can be displayed fully there.
Screen Shot 2021-08-17 at 5 01 23 PM

**Comment by wenluomask** [comment]
Checked.

**Review by zhouhanseng — APPROVED** [review]

**Review by yanzhihong23 — APPROVED** [review]

**Pull request merged**
