### PR TITLE
Fix Japanese Locale

### PR DESCRIPTION
**Pull request by blank71**

### CODE REVIEW

**Comment by neruthes** [comment]
Thanks for the pull request. I believe that this will be better than the existing translation and am wondering if "テーマ" could be even better. Any idea on this?

**Comment by blank71** [comment]
Great. I think "テーマ" is more familiar than "外観".

**Comment by Tedko** [comment]
Ok. Do you mind do another PR on テーマ ?

**Comment by blank71** [comment]
https://github.com/DimensionDev/Maskbook/pull/1397

**Pull request merged**
