### PR TITLE
chore: no unnecessary condition

### PR DESCRIPTION
**Pull request by UncleBill**
MF-0000

2/2 remove no unnecessary condition

### CODE REVIEW

**Review by Jack-Works — DISMISSED** [review]
ping me if you think this can be merged.

**Review by guanbinrui — DISMISSED** [review]

**Comment by guanbinrui** [comment]
Should we use eslint autofix this?

**Comment by UncleBill** [comment]
> Should we use eslint autofix this?

Some conditions could fail at runtime.

**Comment by Jack-Works** [comment]
> > Should we use eslint autofix this?
> 
> Some conditions could fail at runtime.

this means the type information is incorrect, IMO we should fix the type and start to use eslint.

**Comment by UncleBill** [comment]
> > > Should we use eslint autofix this?
> > 
> > 
> > Some conditions could fail at runtime.
> 
> this means the type information is incorrect, IMO we should fix the type and start to use eslint.

External APIs are not 100 percents promising.

**Comment by Jack-Works** [comment]
> External APIs are not 100 percents promising.

Can you give an example? Does that type come from npm? In that case, I agree it's hard to fix, but if that case isn't much, we can case-by-case ignore those and apply auto-fix for the rest.

**Comment by UncleBill** [comment]
> > External APIs are not 100 percents promising.
> 
> Can you give an example? Does that type come from npm? In that case, I agree it's hard to fix, but if that case isn't much, we can case-by-case ignore those and apply auto-fix for the rest.

There used to be a few. Might not from npm packages but some external APIs which are unpredictable and sometimes unstable. That's why runtime could fail by chance.

**Comment by UncleBill** [comment]
There comes a live issue https://mask.atlassian.net/browse/MF-6056

**Comment by Jack-Works** [comment]
> There comes a live issue [mask.atlassian.net/browse/MF-6056](https://mask.atlassian.net/browse/MF-6056)

I think we should stop casting types in our code like this:

```js
const data = await fetchJSON<ApiType>(url)
```

but like this:

```js
import { } from 'zod'
const _data = await fetchJSON(url) // _data is type unknown
const data = object({
   // ...
}).safeParse()
```

**Comment by Jack-Works** [comment]
I think you can merge this if you think this PR is ready, but I still hope we can enable the eslint rule to enforce it.

**Pull request merged**
