### PR TITLE
chore: token panel max

### LINKED ISSUE #4199: [Bug] Red packet set "amount per share" number when click max
### How to reproduce?
image

### What happened?
The amount per share is 9.627

### What should happen?
The amount per share is 9.627 / 5(shares)

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by zhouhanseng**
closes #4199

### CODE REVIEW

**Comment by zhouhanseng** [comment]
@DimensionDev/qa

**Review by guanbinrui — DISMISSED** [review]

**Comment by wenluomask** [comment]
This change should only for average slit mode. For random, you should keep the old method(The maximum is the current balance).

**Comment by zhouhanseng** [comment]
@wenluomask fixed

**Comment by wenluomask** [comment]
It didn't calculate accurately for average split mode when I tried 50 and 100.

**Comment by wenluomask** [comment]
Checked.

**Review by guanbinrui — APPROVED** [review]

**Review by Jack-Works — APPROVED** [review]

**Pull request merged**
