### PR TITLE
chore: reduce images

### PR DESCRIPTION
**Pull request by septs**
closes #

### CODE REVIEW

**Comment by septs** [comment]
@guanbinrui `packages/maskbook/src/plugins/ITO/assets/share-background.jpg`
origin file is PNG format, the current replace JPEG format
but i don't know now the image border radius angles

(wait on monday, plz designer measure this parameter)

**Review by guanbinrui — APPROVED** [review]

**Comment by guanbinrui** [comment]
> but i don't know now the image border radius

CC @zhouhanseng

**Comment by UncleBill** [comment]
image

https://github.com/DimensionDev/Maskbook/blob/753fa5086ab27dbda67738d046bfcd45b52d85f1/packages/maskbook/src/plugins/ITO/UI/ShareDialog.tsx#L48-L49

Sizes of these three images are too big for the container of `share-background.jpg`, maybe 2x or 3x is enough. Could you resize them as well?

**Comment by septs** [comment]
> Could you resize them as well?

Oversampling can be anti-aliased.

**Comment by septs** [comment]
@OiCkilL

**Review by zhouhanseng — APPROVED** [review]

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
