### PR TITLE
fix: snapshot api

### LINKED ISSUE #4909: [Bug]  undefined appears in snapshot plugin
## Bug Info

image

### How to reproduce?

1. https://twitter.com/0xTycoon/status/1463355982747095041
2.
3.

### Mask Version:

- [ ] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [ ] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [ ] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by zhouhanseng**
close #4909

image

### CODE REVIEW

**Comment by zhouhanseng** [comment]
@DimensionDev/qa

**Review by guanbinrui — DISMISSED** [review]

**Review by guanbinrui — DISMISSED** [review]

**Comment by wenluomask** [comment]
Checked.

**Comment by zhouhanseng** [comment]
@wenluomask fixed

**Comment by wenluomask** [comment]
Checked.

**Pull request merged**
