### PR TITLE
chore: remove bsc swapper

### PR DESCRIPTION
**Pull request by zhouhanseng**
SUSHISWAP SASHIMISWAP does not support bsc. try bnb <=> usdt

### CODE REVIEW

**Comment by guanbinrui** [comment]
Actually, They are working on BSC.

**Comment by zhouhanseng** [comment]
The amount of 1 bnb to usdt is wrong， should be 300.

**Comment by guanbinrui** [comment]
> The amount of 1 bnb to usdt is wrong, should be 300.

Please try to use the original apps.

+ https://app.sushi.com/swap
+ https://bsc.sashimi.cool/app/#/swap

**Comment by zhouhanseng** [comment]
Try bnb <=> usdc.

Pancake: 1: 304.618

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
