### PR TITLE
feat: upgrade material-ui

### PR DESCRIPTION
**Pull request by nuanyang233**

### CODE REVIEW

**Comment by septs** [comment]
@jk234ert plz test this pr

**Comment by nuanyang233** [comment]
I found a [problem](https://github.com/mui-org/material-ui/issues/25011#issuecomment-787986175) in test, let's wait for a reply from materail team

**Comment by nuanyang233** [comment]
!!! Don't merge this branch until mobile testing is done !!!

**Comment by jk234ert** [comment]
Found 2 new issues on iOS, that confirmed to be not existing on the 1.29.0 release version:
1. Market info of searched tokens disappeared, on 1.29.0 the market info, only the "Pull down to refresh arrow indicator" visible, but this indicator should be hidden in normal state and appears when the user scrolls down. Guess something related to the offset is broken :
IMG_2205

on 1.29.0:
IMG_AA50D8EE6DF4-1

2. The segment icon becomes transparent while being selected:
IMG_2204
IMG_2203

**Comment by jk234ert** [comment]
Still testing on Android...

**Comment by Jack-Works** [comment]
@nuanyang233 hi https://github.com/mui-org/material-ui/releases/tag/v5.0.0-alpha.27 has released

**Comment by nuanyang233** [comment]
@jk234ert Hi,  i have upgraded material-ui to 5.0.0-alpha.27, plz re-test on mobile

**Pull request closed without merging**
