### PR TITLE
Can not decrypt tweet in tread view

### LINKED ISSUE #601: [Bug] Twitter RT + comment UX bug
# Bug Report

### System

- OS:
- OS Version:

### Browser

- Browser: Chrome
- Browser Version: Latest stable

### Maskbook

- Maskbook Version: latest stable chrome store ver
- Installation: /* May be "Store", "ZIP", or "Self-Complied" */
- Build Commit: Optionally attach a Commit ID, if it is from an pre-release branch head

## Bug Info

Alice post encrypted tweet 'Alice1'
Bob RT that tweet of Alice and comment encrypted content 'Bob1'
-- Bob's RT will be decrypted as 'Alice1' (I mean the UX will only decrypt the original content)

### Expected Behavior

/* Write the expected behavior here. */

### Actual Behavior

Screen Shot 2020-01-03 at 02 55 05

/* Write the actual behavior here. */

### How To Reproduce

/* Specify how it may be produced here. */

NOTE: not urgent. but annoying for any frequent twitter user. Better fix this early

### PR DESCRIPTION
**Pull request by guanbinrui**
close #601

### CODE REVIEW

**Comment by SunriseFox** [comment]
Seems not matching twitter detail page but only timeline

**Comment by guanbinrui** [comment]
@SunriseFox I need do more testing.

**Comment by Jack-Works** [comment]
@guanbinrui does this fix ready? and should I include it in 1.9.0?

**Comment by guanbinrui** [comment]
> @guanbinrui does this fix ready? and should I include it in 1.9.0?

It OK now.

**Pull request merged**
