### PR TITLE
Red packet

### PR DESCRIPTION
**Pull request by Jack-Works**

### CODE REVIEW

**Comment by neruthes** [comment]
Reception review starting now?

**Comment by neruthes** [comment]
**Discussion summary:**

This pull request is used for diff comparison purposes only. Should not merge or pay attention.

**Comment by Jack-Works** [comment]
We need a serious code review after the holiday.

**Comment by Tedko** [comment]
Indeed.

**Comment by neruthes** [comment]
Even revert it

**Comment by neruthes** [comment]
This pull request was originally described as diff comparison only. This merge is a violation of operation standards. Will sanitize.

**Pull request merged**
