### PR TITLE
feat: mobile check persona

### PR DESCRIPTION
**Pull request by zhouhanseng**
@jk234ert

### CODE REVIEW

**Comment by septs** [comment]
CC @Jack-Works

**Comment by Jack-Works** [comment]
We've decided to use another mechanism in the last meeting @zhouhanseng

**Comment by jk234ert** [comment]
Since our injected scripts take some time (5-6 secs on outdated device models) to be executed, native could not get the actual timeframe to evaluate any function to get the value from JS side like "currently connected personas". 
IMO we still need such kind of "mobileIsMyPersonasInitialized" for native to decide the routing destination on app launch.

**Review by jk234ert — APPROVED** [review]

**Comment by Jack-Works** [comment]
@jk234ert No it doesn't rely on "injected scripts". The background script takes the job of responsing.

**Pull request merged**
