### PR TITLE
Remove inline background image

### PR DESCRIPTION
**Pull request by guanbinrui**

### CODE REVIEW

**Comment by Jack-Works** [comment]
Umm I'd like to avoid webpack specified code (like import a png) but whatever, maybe it is ok to me.

**Comment by guanbinrui** [comment]
> Umm I'd like to avoid webpack specified code (like import a png) but whatever, maybe it is ok to me.

Inlining background image is not good.

I was blocked by when transpiling the TS modules in `setup.srr.js`. Any suggestions for that?

**Comment by Jack-Works** [comment]
Put the image in public/ folder and load it by path

**Comment by Tedko** [comment]
yes good idea-

**Comment by guanbinrui** [comment]
Umm... Wanna keeping wallet stuff in its own folder. Maybe `cp` those assets before building?

**Comment by Jack-Works** [comment]
add a plug-in folder in public folder

**Comment by guanbinrui** [comment]
> add a plug-in folder in public folder

Not a bad idea.

**Comment by Jack-Works** [comment]
Umm wait. Why the target branch is released?

**Comment by guanbinrui** [comment]
> Umm wait. Why the target branch is released?

It's part of [M3A](https://github.com/DimensionDev/Maskbook/milestone/8).

**Pull request merged**
