### PR TITLE
fix: style issue in PoolTogether

### LINKED ISSUE #4690: [Bug] Style issue in PoolTogether
### How to reproduce?

image

### Mask Version:

- [x] (Browser) Installed from the extension store (version: )
- [ ] (App) Installed from the app store (version: )
- [ ] master branch
- [ ] Build of version/commit hash:

(Please write down build command/flags if there is anything special)

### System

 
- [ ] Windows 10
- [x] Mac OS X Catalina
- [ ] Linux: 

### Platform/Browser

 
- [x] Latest Chrome (stable channel)
- [ ] Latest Firefox (stable channel)
- [ ] Android 11
- [ ] iOS 14

### PR DESCRIPTION
**Pull request by lelenei**
closes #4690

### CODE REVIEW

**Comment by guanbinrui** [comment]
Hi, @lelenei Could you please give a preview image?

**Review by Jack-Works — APPROVED** [review]

**Comment by lelenei** [comment]
image

**Comment by guanbinrui** [comment]
@DimensionDev/qa

**Comment by AinuX** [comment]
Checked

**Pull request merged**
