### PR TITLE
fix: useMenu warning

### PR DESCRIPTION
**Pull request by septs**

### CODE REVIEW

**Comment by septs** [comment]
CC @zhouhanseng 

https://github.com/DimensionDev/Maskbook/blob/73135381ea3f249798b269f9a03d8cbc31196cb0/packages/maskbook/src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx#L114-L116

```
react-dom.development.js?e52a:67 Warning: validateDOMNesting(...): <div> cannot appear as a child of <tbody>.
    at div
    at ViewDetailed (webpack-internal:///./src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx:116:13)
    at tbody
    at TableBody (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/TableBody/TableBody.js:33:5)
    at WithStyles(ForwardRef(TableBody)) (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/withStyles/withStyles.js:64:7)
    at table
    at Table (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Table/Table.js:44:5)
    at WithStyles(ForwardRef(Table)) (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/withStyles/withStyles.js:64:7)
    at div
    at TableContainer (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/TableContainer/TableContainer.js:28:5)
    at WithStyles(ForwardRef(TableContainer)) (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/withStyles/withStyles.js:64:7)
    at WalletAssetsTable (webpack-internal:///./src/extension/options-page/DashboardComponents/WalletAssetsTable.tsx:175:79)
    at div
    at eval (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Box/Box.js:26:5)
    at eval (webpack-internal:///../../node_modules/.pnpm/@emotion/react@11.1.5_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@emotion/react/dist/emotion-element-4fbd89c5.browser.esm.js:45:66)
    at Box (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Box/Box.js:66:77)
    at div
    at eval (webpack-internal:///./src/extension/options-page/DashboardComponents/WalletContent.tsx:103:84)
    at div
    at div
    at div
    at InnerThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/styles/ThemeProvider.js:20:67)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/styles/ThemeProvider.js:39:5)
    at div
    at main
    at section
    at Transition (webpack-internal:///../../node_modules/.pnpm/react-transition-group@4.4.1_374ef64a62bbfede0e3ba5755a0e45c5/node_modules/react-transition-group/esm/Transition.js:130:30)
    at Fade (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Fade/Fade.js:45:5)
    at DashboardRouterContainer (webpack-internal:///./src/extension/options-page/DashboardRouters/Container.tsx:168:13)
    at DashboardWalletsRouter (webpack-internal:///./src/extension/options-page/DashboardRouters/Wallets.tsx:117:79)
    at ErrorBoundary (webpack-internal:///../theme/dist/src/Components/ErrorBoundary/ErrorBoundary.js:30:9)
    at Route (webpack-internal:///../../node_modules/.pnpm/react-router@5.2.0/node_modules/react-router/esm/react-router.js:464:29)
    at Switch (webpack-internal:///../../node_modules/.pnpm/react-router@5.2.0/node_modules/react-router/esm/react-router.js:670:29)
    at div
    at div
    at DashboardUI (webpack-internal:///./src/extension/options-page/index.tsx:167:79)
    at div
    at DashboardBlurContextUI (webpack-internal:///./src/extension/options-page/DashboardContexts/BlurContext.tsx:60:35)
    at Router (webpack-internal:///../../node_modules/.pnpm/react-router@5.2.0/node_modules/react-router/esm/react-router.js:93:30)
    at HashRouter (webpack-internal:///../../node_modules/.pnpm/react-router-dom@5.2.0/node_modules/react-router-dom/esm/react-router-dom.js:106:35)
    at NoSsr (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/NoSsr/NoSsr.js:26:5)
    at SnackbarProvider (webpack-internal:///../../node_modules/.pnpm/notistack@1.0.5/node_modules/notistack/dist/notistack.esm.js:756:24)
    at DashboardSnackbarProvider (webpack-internal:///./src/extension/options-page/DashboardComponents/DashboardSnackbar.tsx:42:38)
    at InnerThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/styles/ThemeProvider.js:20:67)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/ThemeProvider/ThemeProvider.js:45:5)
    at ThemeProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/styles/ThemeProvider.js:39:5)
    at StyledEngineProvider (webpack-internal:///../../node_modules/.pnpm/@material-ui/styled-engine@5.0.0-alpha.24_0460b069dbdf3e75fbdd3c9d1ec5d573/node_modules/@material-ui/styled-engine/StyledEngineProvider/StyledEngineProvider.js:22:5)
    at SnackbarProvider (webpack-internal:///../../node_modules/.pnpm/notistack@1.0.5/node_modules/notistack/dist/notistack.esm.js:756:24)
    at ErrorBoundary (webpack-internal:///../theme/dist/src/Components/ErrorBoundary/ErrorBoundary.js:30:9)
    at I18nextProvider (webpack-internal:///../../node_modules/.pnpm/react-i18next@11.8.8_5a7fb893a584fd9585bb57d41ac49552/node_modules/react-i18next/dist/es/I18nextProvider.js:10:19)
    at Dashboard (webpack-internal:///./src/extension/options-page/index.tsx:240:448)
    at ErrorBoundary (webpack-internal:///../theme/dist/src/Components/ErrorBoundary/ErrorBoundary.js:30:9)
```

**Comment by septs** [comment]
CC @zhouhanseng 

https://github.com/DimensionDev/Maskbook/blob/73135381ea3f249798b269f9a03d8cbc31196cb0/packages/maskbook/src/extension/options-page/DashboardComponents/TokenActionsBar.tsx#L38

```
react-dom.development.js?e52a:67 Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `ForwardRef(Menu)`.
    at TokenActionsMenu (webpack-internal:///./src/extension/options-page/DashboardComponents/TokenActionsBar.tsx:47:13)
```

**Comment by septs** [comment]
https://github.com/DimensionDev/Maskbook/blob/73135381ea3f249798b269f9a03d8cbc31196cb0/packages/maskbook/src/extension/options-page/DashboardDialogs/Wallet.tsx#L389

```
Warning: React does not recognize the `ComponentProps` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `componentprops` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at div
    at Portal (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Portal/Portal.js:33:5)
    at Modal (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Modal/Modal.js:82:77)
    at Dialog (webpack-internal:///../../node_modules/.pnpm/@material-ui/core@5.0.0-alpha.24_52c8ffd459e292dfd249c4216f4f400c/node_modules/@material-ui/core/Dialog/Dialog.js:182:5)
    at WithStyles(ForwardRef(Dialog)) (webpack-internal:///../../node_modules/.pnpm/@material-ui/styles@5.0.0-alpha.24_4d2b26b4d7a4b6f1109644d22ac504b1/node_modules/@material-ui/styles/withStyles/withStyles.js:64:7)
    at DashboardDialogCore (webpack-internal:///./src/extension/options-page/DashboardDialogs/Base.tsx:68:13)
    at DashboardWalletBackupDialog (webpack-internal:///./src/extension/options-page/DashboardDialogs/Wallet.tsx:280:79)
```

**Comment by septs** [comment]
@zhouhanseng other warning, plz open new pr.

**Review by guanbinrui — APPROVED** [review]

**Comment by zhouhanseng** [comment]
@septs @guanbinrui this pr breaks ui, I will try to fix it, please don't release

image

**Comment by septs** [comment]
@zhouhanseng the previous one commit is broken.

**Pull request merged**
