### PR TITLE
feat: Support minds.io

### PR DESCRIPTION
**Pull request by sevak-crypto**
So im working on implementing minds into mask but when i try to type in the popup, i am unable to do it

I had changed 11 files which were all from the social network adapter folder. They were Base.ts, Index.ts, shared.ts, ui-provider.ts, worker-provider.ts, ui.ts, setupGuide.ts, Types.ts, post.ts. I had also created a file called Identity-provider.ts

Thx 
Screenshot (150)

### CODE REVIEW

**Comment by sevak-crypto** [comment]
> So im working on implementing minds into mask but when i try to type in the popup, i am unable to do it
> 
> I had changed 11 files which were all from the social network adapter folder. They were Base.ts, Index.ts, shared.ts, ui-provider.ts, worker-provider.ts, ui.ts, setupGuide.ts, Types.ts, post.ts. I had also created a file called Identity-provider.ts
> 
> Thx
> Screenshot (150)

**Comment by Jack-Works** [comment]
I don't see your changes. @sevak-crypto https://github.com/DimensionDev/Maskbook/pull/2640/files
Where's your editing?

**Comment by sevak-crypto** [comment]
> I don't see your changes. @sevak-crypto https://github.com/DimensionDev/Maskbook/pull/2640/files
> Where's your editing?

Can I send code just through the messages because Im not sure how to put it into the file changes part

**Comment by sevak-crypto** [comment]
base.ts

`import type { SocialNetwork, SocialNetworkWorker } from '../../social-network/types'

const id = 'minds.com'
export const mindsBase: SocialNetwork.Base = {
    networkIdentifier: id,
    shouldActivate(location) {
        return location.host.endsWith(id)
    },
}
export const mindsWorkerBase: SocialNetworkWorker.WorkerBase & SocialNetwork.Base = {
    ...mindsBase,
    gunNetworkHint: id,
}
`

**Comment by sevak-crypto** [comment]
shared.ts 

`import type { SocialNetwork } from '../../social-network/types'
import { mindsBase } from './base'

export const mindsShared: SocialNetwork.Shared & SocialNetwork.Base = {
    ...mindsBase,
    utils: {
        getHomePage: () => 'https://www.minds.com/',
    },
}
`

**Comment by sevak-crypto** [comment]
Ui provider.ts

`import { SocialNetworkUI, stateCreator } from '../../social-network'
import { mindsShared } from './shared'
import { mindsBase } from './base'
import { IdentityProviderMinds } from './collecting/identity-provider'
import { PostProviderMinds } from './collecting/post'
import { createTaskStartSetupGuideDefault } from '../../social-network/defaults'
const origins = ['https://www.minds.com/*', 'https://m.minds.com/*', 'https://minds.com/*']
const define: SocialNetworkUI.Definition = {
    ...mindsShared,
    ...mindsBase,
    automation: {},
    collecting: {
        identityProvider: IdentityProviderMinds,
        postsProvider: PostProviderMinds,
    },
    configuration: {
        setupWizard: {
            disableSayHello: true,
        },
    },
    customization: {},
    init(signal) {
        const friends = stateCreator.friends()
        const profiles = stateCreator.profiles()
        return { friends, profiles }
    },
    injection: {
        setupWizard: createTaskStartSetupGuideDefault(mindsBase.networkIdentifier),
    },
    permission: {
        request: () => browser.permissions.request({ origins }),
        has: () => browser.permissions.contains({ origins }),
    },
}
export default define
`

**Comment by sevak-crypto** [comment]
worker-provider.ts 

`import type { SocialNetworkWorker } from '../../social-network'
import { mindsWorkerBase } from './base'
import { mindsShared } from './shared'
const define: SocialNetworkWorker.Definition = {
    ...mindsWorkerBase,
    ...mindsShared,
    tasks: {},
}
export default define
`

**Comment by sevak-crypto** [comment]
Identity-provider.ts (newly created)

`import { SocialNetworkUI, creator } from '../../../social-network'
import { ProfileIdentifier } from '@dimensiondev/maskbook-shared'
import { mindsBase } from '../base'
import { openDB } from 'idb'
export const IdentityProviderMinds: SocialNetworkUI.CollectingCapabilities.IdentityResolveProvider = {
    async start(signal) {
        const ref = this.lastRecognized
        update()

        async function update() {
            if (signal.aborted) return
            const val = await query()
            if (val) ref.value = val
            setTimeout(update, 10 * 1000)
        }
    },
    lastRecognized: creator.IdentityResolveProviderLastRecognized(),
}

async function query(): Promise<null | SocialNetworkUI.CollectingCapabilities.IdentityResolved> {
    const db = await openDB('redux', 1, {
        upgrade: () => {
            db.createObjectStore('paths')
        },
    })
    const tx = db.transaction('paths', 'readonly')
    const id = await tx.store.get('users.viewerId')
    if (!id) return null
    const detail = (await tx.store.get('users.users'))[id]
    db.close()
    return {
        identifier: new ProfileIdentifier(mindsBase.networkIdentifier, detail.username),
        avatar: detail.profilePictureUrl,
        nickname: detail.fullName,
    }
}
`

**Comment by sevak-crypto** [comment]
SetupGuide.tsx line 250 - 268

`    export namespace Configuration {
        export interface Define {
            steganography?: SteganographyConfig
            setupWizard?: SetupWizardConfig
        }
        export interface SteganographyConfig {
            grayscaleAlgorithm?: GrayscaleAlgorithm
@@ -259,6 +260,9 @@ export namespace SocialNetworkUI {
             */
            password?(): string
        }
        export interface SetupWizardConfig {
            disableSayHello?: boolean
        }
    }
}`

**Comment by sevak-crypto** [comment]
setupGuide.tsx 586 - 602 

    const onNext = async () => {
        switch (step) {
            case SetupGuideStep.FindUsername:
                currentSetupGuideStatus[ui.networkIdentifier].value = stringify({
                    status: SetupGuideStep.SayHelloWorld,
                    username,
                    persona: persona.toText(),
                } as SetupGuideCrossContextStatus)
                if (activatedSocialNetworkUI.configuration.setupWizard?.disableSayHello) {
                    onConnect().then(onClose)
                } else {
                    ui.automation.redirect?.newsFeed?.()
                    setStep(SetupGuideStep.SayHelloWorld)
                }
                break
            case SetupGuideStep.SayHelloWorld:

**Comment by sevak-crypto** [comment]
post.ts 

import { DOMProxy, LiveSelector, MutationObserverWatcher } from '@dimensiondev/holoflows-kit'
import type { SocialNetworkUI } from '../../../social-network/types'
import { creator } from '../../../social-network/utils'
import { PostInfo } from '../../../social-network/PostInfo'
import { TypedMessage, makeTypedMessageImage, makeTypedMessageCompound } from '../../../protocols/typed-message'
import { startWatch } from '../../../utils/watcher'
import { ProfileIdentifier } from '@dimensiondev/maskbook-shared'
import { mindsBase } from '../base'

const posts = new LiveSelector().querySelectorAll<HTMLDivElement>(
    'main[role="main"] article[role="presentation"][tabindex="-1"]',
)

export const PostProviderMinds: SocialNetworkUI.CollectingCapabilities.PostsProvider = {
    posts: creator.PostProviderStore(),
    start(signal) {
        collectPostsMindsInner(this.posts, signal)
    },
}
function collectPostsMindsInner(
    store: SocialNetworkUI.CollectingCapabilities.PostsProvider['posts'],
    signal: AbortSignal,
) {
    startWatch(
        new MutationObserverWatcher(posts).useForeach((node, key, metadata) => {
            const info: PostInfo = new (class extends PostInfo {
                commentsSelector = undefined
                commentBoxSelector = undefined
                get rootNode() {
                    return node
                }
                rootNodeProxy = metadata
                postContentNode = metadata.realCurrent!
            })()

            store.set(metadata, info)
            function collectPostInfo() {
                const nextTypedMessage: TypedMessage[] = []
                info.postBy.value = getPostBy(metadata)
                info.postID.value = getPostID(metadata)
                const img = node.querySelectorAll('img')[1]
                if (img) {
                    nextTypedMessage.push(makeTypedMessageImage(img.src, { height: img.height, width: img.width }))
                } else nextTypedMessage.push(makeTypedMessageImage(''))
                info.postContent.value = ''
                info.postMessage.value = makeTypedMessageCompound(nextTypedMessage)
            }
            collectPostInfo()
            return {
                onNodeMutation: collectPostInfo,
                onTargetChanged: collectPostInfo,
                onRemove: () => store.delete(metadata),
            }
        }),
        signal,
    )
}

function getPostBy(node: DOMProxy): ProfileIdentifier {
    // the first a
    const author = node.current.querySelector('a')
    if (!author) return ProfileIdentifier.unknown
    const href = new URL(author.href).pathname
    if (href.startsWith('/') && href.endsWith('/') && href.slice(1, -1).includes('/') === false) {
        return new ProfileIdentifier(mindsBase.networkIdentifier, href.slice(1, -1))
    }
    return ProfileIdentifier.unknown
}
function getPostID(node: DOMProxy): null | string {
    return node.current?.querySelector<HTMLAnchorElement>('a[href^="/p/"]')?.href.match(/\/p\/(.+)\/.+/)?.[1] || null
}

**Comment by sevak-crypto** [comment]
index.ts (in minds.io folder)

`import { defineSocialNetworkUI, defineSocialNetworkWorker } from '../../social-network'
import { mindsBase, mindsWorkerBase } from './base'

defineSocialNetworkUI({
    ...mindsBase,
    load: () => import('./ui-provider'),
    hotModuleReload(callback) {
        if (module.hot) {
            module.hot.accept('./ui-provider.ts', async () => {
                callback((await import('./ui-provider')).default)
            })
        }
    },
})

defineSocialNetworkWorker({
    ...mindsWorkerBase,
    load: () => import('./worker-provider'),
    hotModuleReload(callback) {
        if (module.hot) {
            module.hot.accept('./worker-provider.ts', async () => {
                callback((await import('./worker-provider')).default)
            })
        }
    },
})
`

**Comment by Jack-Works** [comment]
please use git to commit those files thanks

**Comment by yisiliu** [comment]
> > I don't see your changes. @sevak-crypto https://github.com/DimensionDev/Maskbook/pull/2640/files
> > Where's your editing?
> 
> Can I send code just through the messages because Im not sure how to put it into the file changes part

@sevak-crypto 
Do this on your forked repo

```
> git add .
> git commit -m "Add minds.com support"
> git push origin master 
```

**Comment by sevak-crypto** [comment]
> > > I don't see your changes. @sevak-crypto https://github.com/DimensionDev/Maskbook/pull/2640/files
> > > Where's your editing?
> > 
> > 
> > Can I send code just through the messages because Im not sure how to put it into the file changes part
> 
> @sevak-crypto
> Do this on your forked repo
> 
> ```
> > git add .
> > git commit -m "Add minds.com support"
> > git push origin master 
> ```

Do i have to clone my repo

**Comment by sevak-crypto** [comment]
j

> > > > I don't see your changes. @sevak-crypto https://github.com/DimensionDev/Maskbook/pull/2640/files
> > > > Where's your editing?
> > > 
> > > 
> > > Can I send code just through the messages because Im not sure how to put it into the file changes part
> > 
> > 
> > @sevak-crypto
> > Do this on your forked repo
> > ```
> > > git add .
> > > git commit -m "Add minds.com support"
> > > git push origin master 
> > ```
> 
> Do i have to clone my repo

Just doing the git commands

**Comment by sevak-crypto** [comment]
> git push origin master

why is this happening 
Screenshot (154)

**Comment by yisiliu** [comment]
> > git push origin master
> 
> why is this happening
> Screenshot (154)

This is not how it works. You'd better learn some git before trying to contribute to this bounty since if not, it's gonna waste your time. You need to work on your forked version instead of the original one.

**Pull request closed without merging**
