### PR TITLE
feat: add Clv Wallet connector

### PR DESCRIPTION
**Pull request by ldy0909061**
This fix is for the issues of the test of last commit
- Failed to switch network smoothly in extension. Since I change network from Ether to BSC, Mask disconnect the wallet;
---- fix: this is fixed and is published with clv wallet 6.1.2
- Failed to connect wallet to persona by CLVWallet;
---- fix: this is disabled, clv wallet will not appear here
- Extreme high gas fee to create an ITO by CLVWallet;Higher gas fee spent for NFT transfer;
---- fix: for these two fee issues, we test related case, and found our fee displayed is similar as metamask, is it ok to consider these two issues as passed?

## Description

Successor of #7896.
Closes https://mask.atlassian.net/browse/MF-2652

Closes # (NO_ISSUE)

## Type of change

- [ ] Documentation
- [ ] Code refactoring (Restructuring existing code w/o changing its observable behavior)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (a fix or feature that would make something no longer possible to do/require old user must upgrade their Mask Network to this new version)

## Checklist

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
  - [ ] I have removed all in development `console.log`s
  - [ ] I have removed all commented code.
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have read [Internationalization Guide](https://github.com/DimensionDev/Maskbook/blob/develop/docs/i18n-guide.md) and moved text fields to the i18n JSON file.

If this PR depends on external APIs:

- [ ] I have configured those APIs with CORS headers to let extension requests get passed. 
  - chrome extension: `chrome-extension://[id]`
  - firefox extension: `moz-extension://[id]`
- [ ] I have delegated all web requests to the background service via the internal RPC bridge.

### CODE REVIEW

**Review by guanbinrui — DISMISSED** [review]

**Comment by wenluomask** [comment]
Hi, could you please merge our latest version 2.16 then I can make further testing. Here are some issues I found:

1. Since Mask supports most of EVM chains, CLV wallet is supposed to be one of option if CLV also supports the same chain;
截屏2022-11-21 15 16 19

2. Still failed to switch network smoothly in extension. Currently BSC works, but wallet will be disconnected if switches to other chains except for ETH, Polygon or BSC;
截屏2022-11-21 15 04 24

**Comment by ldy0909061** [comment]
ok, I will merge the code and add more chains supported by both clv and mask, 
for issue 2, now we only add eth, bsc and polygon in the supported list, so switch to other chain will not work

**Comment by ldy0909061** [comment]
hi, merged mask 2.16 code, and update clv code, please check

**Comment by wenluomask** [comment]
As long as CLV can switch to chains that Mask also supports, we have to consider our user experience. I checked the latest version of pr, Mask can connect CLV wallet successfully by any EVM chains. However, the issue 2 still exists.  
If we find out the chains are not supported, we will lead users to switch chain. You can check this video I provided below to fix issue 2.

https://user-images.githubusercontent.com/85149605/203251517-eda893ea-505a-4e0c-a485-d5317046eac9.mov

**Comment by ldy0909061** [comment]
Ok, I will test this case on my side.

**Comment by wenluomask** [comment]
Hi, I am really appreciate your effort. I installed the CLV wallet you provided and tried again. Currently our switch buttons can make the wallet to switch chain successfully. You are almost done! But the issue #2 will still happen if I change chain from ETH to the other chains in wallet.  Please check the video below.

https://user-images.githubusercontent.com/85149605/203807677-289a2ffd-9756-42a6-823d-154c0944c9f8.mov

**Comment by wenluomask** [comment]
Issue fixed! Thanks a lot!

**Review by guanbinrui — APPROVED** [review]

**Pull request merged**
